[project]
name = "rone-arena-api"
version = "1.0.2"
description = "Unofficial community data API for the game Mobile Legends: Bang Bang"
readme = "README.md"
license = { text = "BSD-3-Clause" }
authors = [
    { name = "ridwaanhall" }
]
requires-python = ">=3.10"

dependencies = [
    "fastapi[standard]>=0.135.2",
    "requests>=2.32.0,<3",
    "cryptography==50.0.0",
    "fastapi-cloud-cli>=0.22.0",
]

[project.urls]
Homepage = "https://arena.rone.dev"
Documentation = "https://arena.rone.dev/api/docs"
Repository = "https://github.com/ridwaanhall/rone-arena-api"
Issues = "https://github.com/ridwaanhall/rone-arena-api/issues"

[tool.uv]
package = false

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest==9.0.3",
]
